* Todas putas

La ministra de igualdad y vicepresidenta del gobierno español, siguiendo la estela europea, encabezada por suecia, y la propuesta de Unidos Podemos, anuncia que se establecerá por ley que cualquier relación sexual que no cuente con un /sí/ expreso será considerado violación.

El derecho regula los actos de la vida civíl y los convierte en trámites establecidos mediante contratos (escritos o verbales). Esta vida civíl está fiscalizada por un Estado, que se arroga el monopolio de la violencia legítima. Frente a nuestra vida civíl, en la que obedecemos leyes, está nuestra vida íntima, en la que nadie puede inmiscuírse sin destruír su intimidad. Hasta hoy, el sexo pertenece a esta última esfera salvo cuando se trata de una transacción comercial en la prostitución.

Ahora bien, si cada vez que vayamos a practicar sexo debemos establecer un contrato verbal, nuestra libido queda también fiscalizada por el Estado y, por ende, fuera de la esfera de lo íntimo. Y ya Tolstoi observaba en su *Sonata a Kreuzer* que cualquier intercambio sexual intermediado por un contrato, (como por ejemplo el matrimonio que regulan el derecho civíl o el eclesiástico) era en el fondo una forma de prostitución. De modo que si entra en vigor la medida anunciada por el gobierno, ante la ley, todas putas. Y luego lo llamarán feminismo.
